### ISSUE TITLE
Not receiving anymore InResponseTo attribute in authentication response

### ISSUE THREAD

**Issue by frankGuadagno** [onelogin/dotnet-saml#21]
HI,
saml is not my main identity provider, so, from time to time I activate it on my application, I noticed that I'm not receiving anymore any information related to "inResponseTo" in my assertion node. Even on root node (another option) I don't see this information. 
Could you please tell me if something is changed or am I missing some condition?
regards,
francesco

**Comment by pitbulk** [comment]
Hi,

is an issue on OneLogin's platform already reported, not related with the dotnet-saml plugin.
