### ISSUE TITLE
Assertion with multiple sigs fails all but the first one.

### ISSUE THREAD

**Issue by OllieJones** [onelogin/dotnet-saml#5]
On the SamlTool.com web site at https://www.samltool.com/generic_sso_res.php  you present an example of a Response with a signed Message and a signed Assertion.

In the second pass through the loop at line 90 of https://github.com/onelogin/dotnet-saml/blob/master/App_Code/Saml.cs the Microsoft furnished `CheckSignature` method returns `false`. (On the first pass it returns `true`).

This doesn't seem right.

**Comment by neilmcguire** [comment]
I am also having this issue. Poked at the Java toolkit to see if they addressed it there, and the Java one doesn't appear to actually check the sigs, just how many there are.

**Comment by couraud** [comment]
Same issue here...

**Comment by neilmcguire** [comment]
Created pull request #6 with fix.

**Comment by LarryEllis** [comment]
This is a bug in .Net's XML signature handling.   See my comment to Neil's commit.

**Comment by OllieJones** [comment]
Thank you for digging in to this issue for me.
