### ISSUE TITLE
NotBefore and NotAfter

### ISSUE THREAD

**Issue by premnair** [onelogin/dotnet-saml#8]
Hello
I tried to use the library and got signature verification and nameid correctly.

It seems the NotBefore and NotAfter tags are ignored as a part of verification. 

Are we planning to add this ?
Thanks
Prem

**Comment by pitbulk** [comment]
New release will be published on Octuber

**Comment by premnair** [comment]
thanks  a lot for the quick reply  !

**Comment by Rodrigo-Andrade** [comment]
any news?
